baseURL = 'https://ch1n3du.github.io/'
languageCode = 'en-us'
title = "ch1n3du's pico adventures"
theme = "PaperMod"

[params]
showBreadCrumbs = true
showReadingTime = true
# showShareButtons = true
showPostNavLinks = true
showCodeCopyButtons = true

[params.homeInfoParams]
# Title = "Hello Stranger,"
# Content = """
# You've stumbled upon my distant shores, herein I try time and time again to fight my boredom.
# 
# """

[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/ch1n3du3/"

[[params.socialIcons]]
name = "github"
url = "https://github.com/Ch1n3du"

[[params.socialIcons]]
name = "discord"
url = ""

[menu]
[[menu.main]]
identifier = "About"
name = "About"
url = "/"
weight = 20

[[menu.main]]
identifier = "Posts"
name = "Posts"
url = "/posts/"

[[menu.main]]
identifier = "Projects"
name = "Projects"
url = "/projects/"
