baseURL = 'https://ch1n3du.github.io/'
languageCode = 'en-us'
title = "pico adventures"
theme = "PaperMod"

[params]
env = "production"
showBreadCrumbs = true
showReadingTime = true
# showShareButtons = true
showPostNavLinks = true
showCodeCopyButtons = true
showToc = true


# [params.homeInfoParams]
# Title = "Hello stranger"
# Content = """"""

[[params.socialIcons]]
name = "twitter"
url = "https://twitter.com/ch1n3du3/"

[[params.socialIcons]]
name = "github"
url = "https://github.com/Ch1n3du"

[[params.socialIcons]]
name = "discord"
url = ""

[menu]
[[menu.main]]
identifier = "about"
name = "about"
url = "/"
weight = 20

[[menu.main]]
identifier = "posts"
name = "posts"
url = "/posts/"

[[menu.main]]
identifier = "projects"
name = "projects"
url = "/projects/"
